### PR TITLE
fix(server): Use improved pcsclite distribution to fix windows reader…

### PR DESCRIPTION
**Pull request by kmb64**

### CODE REVIEW

**Review by microshine — APPROVED** [review]

**Comment by microshine** [comment]
@kmb64 thank you for PR. I published a new version
```
Successfully published:
 - @webcrypto-local/server@1.4.1
```

**Comment by microshine** [comment]
@kmb64 I can't include `@pokusew/pcsclite` module to release. We found that it freezes on some Windows builds. `pcsclite` works fine for the same Windows builds. Looks like the problem is for Windows where Smart Card Resource Manager is disabled

**Comment by kmb64** [comment]
Ah okay, that's disappointing. Were you able to reproduce this issue locally and is there still intention to fix it? 

https://github.com/PeculiarVentures/fortify/issues/355

**Comment by kmb64** [comment]
________________________________

**Pull request merged**
